/**
 * NSMP — Email Setup Script
 * Run: node setup.js
 * Yeh script .env file automatically bana dega
 */

const readline = require('readline');
const fs = require('fs');
const path = require('path');

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
const ask = (q) => new Promise((res) => rl.question(q, res));

const GREEN  = '\x1b[32m';
const YELLOW = '\x1b[33m';
const CYAN   = '\x1b[36m';
const RED    = '\x1b[31m';
const RESET  = '\x1b[0m';
const BOLD   = '\x1b[1m';

async function main() {
  console.clear();
  console.log(`${CYAN}${BOLD}`);
  console.log('╔══════════════════════════════════════════════╗');
  console.log('║      🎓 NSMP — Email Setup Wizard            ║');
  console.log('╚══════════════════════════════════════════════╝');
  console.log(`${RESET}`);

  console.log(`${YELLOW}Yeh script aapki .env file automatically bana dega.${RESET}`);
  console.log(`${YELLOW}Gmail App Password chahiye — neeche steps follow karein:${RESET}\n`);

  console.log(`${BOLD}Gmail App Password kaise banayein:${RESET}`);
  console.log('  1. myaccount.google.com kholen');
  console.log('  2. Security → 2-Step Verification ON karein');
  console.log('  3. Security → App Passwords pe jayein');
  console.log('  4. Select app: Mail | Device: Other (NSMP) → Generate');
  console.log(`  5. ${GREEN}16 character password milega — woh yahan paste karein${RESET}\n`);

  console.log('─'.repeat(48));

  const email = await ask(`\n${CYAN}Aapka Gmail address:${RESET} `);
  const pass  = await ask(`${CYAN}Gmail App Password (16 chars, spaces hatakar):${RESET} `);
  const port  = await ask(`${CYAN}Backend port (Enter = 5000):${RESET} `) || '5000';
  const front = await ask(`${CYAN}Frontend URL (Enter = http://localhost:5173):${RESET} `) || 'http://localhost:5173';

  // Clean password — remove spaces
  const cleanPass = pass.replace(/\s/g, '');

  if (!email.includes('@')) {
    console.log(`\n${RED}❌ Email sahi nahi lagta. Script dobara chalayein.${RESET}`);
    rl.close(); return;
  }
  if (cleanPass.length !== 16) {
    console.log(`\n${YELLOW}⚠️  App Password 16 characters ka hona chahiye (aapne ${cleanPass.length} diye).`);
    console.log(`   Agar aap sure hain to continue karein, warna App Password dobara check karein.${RESET}`);
  }

  const envContent = `# ─────────────────────────────────────────────
# NSMP Backend — Environment Variables
# Generated by setup.js on ${new Date().toLocaleString('en-IN')}
# ─────────────────────────────────────────────

PORT=${port}
JWT_SECRET=nsmp_jwt_${Math.random().toString(36).slice(2)}_${Math.random().toString(36).slice(2)}

# Email (Gmail SMTP)
EMAIL_USER=${email.trim()}
EMAIL_PASS=${cleanPass}

# Frontend URL
FRONTEND_URL=${front.trim()}
`;

  const envPath = path.join(__dirname, '.env');
  fs.writeFileSync(envPath, envContent);

  console.log(`\n${GREEN}${BOLD}✅ .env file successfully bana di!${RESET}`);
  console.log(`${GREEN}   Location: ${envPath}${RESET}\n`);

  // Test email connection
  console.log(`${YELLOW}Email connection test kar raha hun...${RESET}`);
  try {
    const nodemailer = require('nodemailer');
    const transporter = nodemailer.createTransport({
      host: 'smtp.gmail.com', port: 587, secure: false,
      auth: { user: email.trim(), pass: cleanPass },
      tls: { rejectUnauthorized: false },
    });
    await transporter.verify();
    console.log(`${GREEN}${BOLD}✅ Gmail connection successful! Email bhejne ke liye taiyaar hai.${RESET}\n`);
  } catch (err) {
    console.log(`${RED}❌ Gmail connection fail hua: ${err.message}${RESET}`);
    console.log(`${YELLOW}   Possible reasons:`);
    console.log(`   - App Password galat hai`);
    console.log(`   - 2-Step Verification ON nahi hai`);
    console.log(`   - Regular password use kiya App Password ki jagah${RESET}\n`);
  }

  console.log(`${CYAN}${BOLD}Ab server start karein:${RESET}`);
  console.log(`  npm run dev\n`);

  rl.close();
}

main().catch((e) => { console.error(e); rl.close(); });
